CREATE TABLE IF NOT EXISTS backlog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL CHECK(category IN ('ACADEMIC', 'PROJECT', 'EXTRA_LEARNING')),
    description TEXT NOT NULL,
    due_date TEXT,
    priority INTEGER NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('PENDING', 'PROMOTED')) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL CHECK(category IN ('ACADEMIC', 'PROJECT', 'EXTRA_LEARNING')),
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('ACTIVE', 'RESOLVED', 'ABANDONED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id INTEGER NOT NULL,
    report TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(task_id) REFERENCES tasks(id)
);
